version: '2'
services:
  gabledb:
    image: postgres
    container_name: gabledb
    volumes:
      - gabledb:/run
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  gableweb:
    container_name: gableweb
    build: web
    command: python /app/code/manage.py runserver_plus 0.0.0.0:8002
    volumes:
      - ./web/code:/app/code
      - ./web/support:/app/support
    ports:
      - "8002:8002"
    depends_on:
      - gabledb
    environment:
      - VIRTUAL_HOST=gable.dev.559labs.net
      - VIRTUAL_PORT=8002

networks:
  default:
    external:
      name: core_default

volumes:
  gabledb:
    driver: local
